
# networks: list of network configurations, each configuration is a list of layers, each layer is a dictionary with the layer_type and properties
networks:
  - - { layer_type: convolution ,
        bias: True,
        heads:  [
          {
            bias: True,
            labels: {
              head: { label_type: [ primary ] },
              tail: { label_type: [ primary ] },
              bias: { label_type: [primary, index_text] },
            },
            properties:
              { name: distances, values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24] },
          },
          {
            bias: True,
            labels: {
              head: { label_type: [ primary ] },
              tail: { label_type: [ primary ] },
              bias: { label_type: [primary, index_text] },
            },
            properties:
              { name: distances, values: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24] },
          },
          ]

      }
    - { layer_type: linear,
        mode: 'aggr_heads',
        output_features: 10,
        bias: True,
        activation: 'tanh',
    }
    - { layer_type: aggregation,
          bias: True,
          out_dim: 10,
          heads: [1],
          labels: [
            { label_type: [primary] },
          ]
      }
    - { layer_type: reshape}
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 2,
        bias: True,
        activation: 'tanh'
    }
    - { layer_type: reshape}




