datasets:
  - {name: "DHFR", validation_folds: 10, experiment_config_file: "Examples/MultiFeatures/Configs/config_experiment.yml", type: "TUDataset"}
paths:
  data:
    "Examples/MultiFeatures/Data/" # Path to the folder containing the graph data
  properties:
    "Examples/MultiFeatures/Data/Properties/" # Precomputed properties will be loaded from this folder
  labels:
    "Examples/MultiFeatures/Data/Labels/" # Path to the folder containing the labels
  results:
    "Examples/MultiFeatures/Results/" # Results will be saved in this folder
  splits:
    "Examples/MultiFeatures/Data/Splits/" # Path to the folder containing the data splits

input_features: # choose from node_labels, node_features,
  #{name: "node_labels"}
  #{name: "node_labels", transformation: "normalize"}
  #{name: "node_labels", transformation: "unit_circle", features_as_channels: True}
  #{name: "node_labels", transformation: "unit_circle"}
  #{name: "node_features"}
  #{name: "node_features", features_as_channels: True}
  #{name: "all", transformation: "normalize_labels"}
  {name: "all", transformation: "normalize_labels", features_as_channels: True}

aggregation_out_features:
  2
channels:
  1
num_workers:
  1

precision:
  double

dropout:
  - 0.0

bias:
    True

convolution_grad:
    True
aggregation_grad:
    True