paths:
  # define a specific path for each architecture
  results:
    "Examples/GED/Results/SAGE/" # Results will be saved in this folder

networks:
- - { layer_type: linear,
      out_features: 64,
      bias: True,
      activation: torch.nn.Tanh(),
    }
  - { layer_type: sage_convolution,
      bias: True,
      out_channels: 64,
      activation: torch.nn.Tanh(),
      residual: True,
}
  - { layer_type: sage_convolution,
      bias: True,
      out_channels: 64,
      activation: torch.nn.Tanh(),
        residual: True,
}
  - { layer_type: sage_convolution,
      bias: True,
      out_channels: 64,
      activation: torch.nn.Tanh(),
        residual: True,
  }
  - { layer_type: global_pooling,
        mode: mean,
    }
  - { layer_type: linear,
      out_features: 64,
      bias: True,
      activation: torch.nn.Tanh(),
  }
  - { layer_type: linear,
      out_features: 2,
      bias: True,
      activation: torch.nn.Tanh(),
  }


