networks:
  - - { layer_type: convolution ,
      bias: False,
      heads: [ 1 ],
      labels: [
          { label_type: [simple_cycles, primary], max_cycle_length: [6] },
          #{ label_type: [ wl_labeled ], depth: [ 2 ] },
      ],
      properties: [
        { name: distances, values: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
  19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
  39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
  59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
  79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93] },
        #{ name: distances, values: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ] },
      ]
  }
    - { layer_type: convolution ,
        bias: False,
        heads: [ 1 ],
        labels: [
          { label_type: [ simple_cycles, primary ], max_cycle_length: [ 6 ] },
          #{ label_type: [ wl_labeled ], depth: [ 2 ] },
        ],
        properties: [
          { name: distances, values: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
                                       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
                                       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
                                       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
                                       79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93 ] },
          #{ name: distances, values: [ 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ] },
        ]
    }



    - { layer_type: aggregation,
        bias: True,
        heads: [1],
        out_dim: 2,
        labels: [
          {label_type: [wl_labeled], depth: [0] },
          #{ label_type: [simple_cycles, primary], max_cycle_length: [6] },
          #{ label_type: [simple_cycles, primary], max_cycle_length: [10] },
          #{ label_type: [simple_cycles], max_cycle_length: [6] },
          #{ label_type: [ subgraph, primary ], id: [ 0 ] },
        ],
    }


#final_linear_layers:
#  - { input_dimension: 2, output_dimension: 2, bias: True }
  #- { input_dimension: 10, output_dimension: 2, bias: True }

# if subgraph labels are used the corresponding list of subgraphs should be provided here:
subgraphs:
  - "[nx.cycle_graph(6), nx.cycle_graph(7), nx.cycle_graph(8)]"
  - "[nx.cycle_graph(6), nx.cycle_graph(7), nx.cycle_graph(8), nx.cycle_graph(9), nx.cycle_graph(10)]"
  - "[nx.cycle_graph(6), nx.cycle_graph(7), nx.cycle_graph(8), nx.cycle_graph(9), nx.cycle_graph(10), nx.cycle_graph(11), nx.cycle_graph(12)]"







