networks:
  - - { layer_type: convolution ,
      bias: False,
      heads: [
        {
          bias: False,
          labels: {
            head: { label_type: wl_labeled, depth: 1 },
            tail: { label_type: wl_labeled, depth: 1 },
            bias: { label_type: wl_labeled, depth: 1 },
          },
          properties:
            { name: distances, values: [ 0,1,2,3,4 ] },
        },
      ],
  }
    - { layer_type: linear,
        mode: 'aggr_heads',
        output_features: 10,
        bias: True,
        activation: 'tanh',
    }
    - { layer_type: aggregation,
        bias: True,
        out_dim: 10,
        heads: [
          {
            bias: True,
            labels: { label_type: [induced_cycles, primary], min_cycle_length: 6 , max_cycle_length: 6, depth: 0 },
          },
          {
            bias: True,
            labels: { label_type: [induced_cycles, primary], min_cycle_length: 7, max_cycle_length: 7, depth: 0 },
          },
          {
            bias: True,
            labels: { label_type: [induced_cycles, primary], min_cycle_length: 8, max_cycle_length: 8, depth: 0},
          }
        ],
    }
    - { layer_type: reshape}
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 10,
        bias: True,
        activation: 'None'
    }
    - { layer_type: linear,
        mode: 'aggr_features',
        output_features: 1,
        bias: True,
        activation: 'None'
    }
    - { layer_type: reshape}