networks:
  - - { layer_type: convolution ,
        bias: False,
        labels: [
          { label_type: [subgraph, primary], id: 0 }
        ],
        properties: [
          { name: distances, values: [ 0, 3 ] }
        ]
  }
    - { layer_type: aggregation,
        bias: True,
        labels: [
          { label_type: [wl, primary], depth: [2] }
        ]
    }

# if subgraph labels are used the corresponding list of subgraphs should be provided here:
subgraphs:
  - "[nx.cycle_graph(4), nx.cycle_graph(5)]"