device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.1
epochs:
  - 200
scheduler:
  False
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    False
  patience:
    25
networks:
  # mixed models
  - - { layer_type: primary, properties: { name: distances, values: [8] }}
    - { layer_type: primary, properties: { name: distances, values: [4] }}
    - { layer_type: primary }

precision:
  double