device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.05
epochs:
  - 50
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    True
  patience:
    25
networks:
  - - { layer_type: convolution ,
        labels: [
          { label_type: wl, depth: [ 0,1,2,3,4 ] },
          { label_type: simple_cycles, max_cycle_length: [ 3,4,5 ] },
          { label_type: induced_cycles, max_cycle_length: [ 4,5,10,20 ] },
          { label_type: cliques, max_clique_size: [ 3,4,6,10,20,50 ] },
          { label_type: subgraph, id: [ 0,1,2,3 ] }
        ],
        properties: [
          { name: distances, values: [ 1,2 ] },
        ]
  }
    - { layer_type: aggregation,
        labels: [
          { label_type: wl, depth: [ 0,1,2,3,4 ] },
          { label_type: simple_cycles, max_cycle_length: [ 3,4,5 ] },
          { label_type: induced_cycles, max_cycle_length: [ 4,5,10,20 ] },
          { label_type: cliques, max_clique_size: [ 3,4,6,10,20,50 ] },
        ]
    }

# if subgraph labels are used the corresponding list of subgraphs should be provided here:
subgraphs:
  - "[nx.complete_graph(4)]"
  - "[nx.cycle_graph(3), nx.star_graph(1)]"
  - "[nx.cycle_graph(4), nx.star_graph(1)]"
  - "[nx.cycle_graph(3), nx.cycle_graph(4), nx.star_graph(1)]"

precision:
  double