loss:
  - CrossEntropyLoss
networks:
  - - { layer_type: convolution ,
        labels: [
          { label_type: subgraph, id: 0 }
        ],
        properties: [
          { name: distances, values: [ 3 ] }
        ]
  }
    - { layer_type: aggregation,
        labels: [
          { label_type: wl, depth: [0, 1] }
        ]
    }

# if subgraph labels are used the corresponding list of subgraphs should be provided here:
subgraphs:
  - "[nx.cycle_graph(4), nx.cycle_graph(5)]"

input_features: {name: node_labels, transformation: normalize}