loss:
  - CrossEntropyLoss
networks:
  - - { layer_type: convolution ,
        bias: False,
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ],
        properties: [
          { name: distances, values: [ 0, 1 ] }
        ]
  }
    - { layer_type: aggregation,
        bias: True,
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ]
    }
