device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 16
learning_rate:
  - 0.05
epochs:
  - 50
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    True
  patience:
    25
networks:
  - - { layer_type: convolution ,
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ],
        properties: [
          { name: distances, values: [ 1 ] }
        ]
  }
    - { layer_type: aggregation,
        labels: [
          { label_type: simple_cycles, max_cycle_length: [ 10 ] }
        ]
    }

precision:
  double