device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.1
epochs:
  - 200
scheduler:
  False
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    False
  patience:
    25
networks:
  # mixed models
  - - { layer_type: subgraph, id: 0, properties: { name: distances, values: [ 3 ] }}
    - { layer_type: wl, wl_iterations: 1}

# if subgraph labels are used the corresponding list of subgraphs should be provided here:
subgraphs:
  - "[nx.cycle_graph(4), nx.cycle_graph(5)]"

precision:
    double