loss:
  - CrossEntropyLoss
networks:
  # mixed models
  - - { layer_type: convolution ,
        labels: [
          { label_type: primary}
        ],
        properties: [
          { name: distances, values: [ 50 ] }
        ]
      }
    - { layer_type: aggregation,
        labels: [
          { label_type: primary }
        ]
    }

input_features: {name: node_labels, transformation: normalize_positive}
