device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.05
epochs:
  - 50
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    True
  patience:
    25
networks:
  # wl models
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1,2,3] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1,2,3,4,5,6,7,8,9,10] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }

  # cycle models
  - - { layer_type: simple_cycles, max_cycle_length: 10, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: simple_cycles, max_cycle_length: 10 }
  - - { layer_type: simple_cycles, max_cycle_length: 20, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: simple_cycles, max_cycle_length: 20 }

  # mixed models
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: simple_cycles, max_cycle_length: 10 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: simple_cycles, max_cycle_length: 20 }
  - - { layer_type: simple_cycles, max_cycle_length: 10, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000}
  - - { layer_type: simple_cycles, max_cycle_length: 20, properties: { name: distances, values: [1,2,3,4,5,6] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, properties: { name: distances, values: [ 1,2,3,4,5,6 ] }}
    - { layer_type: primary}
  - - { layer_type: simple_cycles, max_cycle_length: 20, properties: { name: distances, values: [ 1,2,3,4,5,6 ] }}
    - { layer_type: primary}
  - - { layer_type: primary, properties: { name: distances, values: [ 1,2,3,4,5,6 ] }}
    - { layer_type: simple_cycles, max_cycle_length: 20 }
  - - { layer_type: primary, properties: { name: distances, values: [ 1,2,3,4,5,6 ] }}
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }

precision:
  double