networks:
  - - { layer_type: convolution ,
        bias: False,
        labels: [
          { label_type: primary}
        ],
        properties: [
          { name: distances, values: [ 0, 8 ] }
        ]
      }
    - { layer_type: convolution ,
        bias: False,
        labels: [
          { label_type: primary}
        ],
        properties: [
          { name: distances, values: [ 0, 4 ] }
        ]
    }
    - { layer_type: aggregation,
        bias: True,
        labels: [
          { label_type: primary }
        ]
    }