datasets:
  # real-world datasets
  - {name: "NCI1", data: "Reproduce_RuleGNN/Data/TUDatasets/", validation_folds: 10, experiment_config_file: "Reproduce_RuleGNN/Configs/config_NCI1.yml", type: "TUDataset"}
  - {name: "NCI109", data: "Reproduce_RuleGNN/Data/TUDatasets/", validation_folds: 10, experiment_config_file: "Reproduce_RuleGNN/Configs/config_NCI1.yml", type: "TUDataset"}
  - {name: "IMDB-BINARY", data: "Reproduce_RuleGNN/Data/TUDatasets/", validation_folds: 10, experiment_config_file: "Reproduce_RuleGNN/Configs/config_IMDB.yml", type: "TUDataset"}
  - {name: "IMDB-MULTI", data: "Reproduce_RuleGNN/Data/TUDatasets/", validation_folds: 10, experiment_config_file: "Reproduce_RuleGNN/Configs/config_IMDB.yml", type: "TUDataset"}

paths:
  # all the paths are relative to the PYTHONPATH path, can be also defined dataset-wise in the experiment_config_file
  properties:
    "Reproduce_RuleGNN/Data/Properties/" # Precomputed properties will be loaded from this folder
  labels:
    "Reproduce_RuleGNN/Data/Labels/" # Path to the folder containing the labels
  splits:
    "Reproduce_RuleGNN/Data/SplitsSimple/" # Path to the folder containing the data splits
  results:
    "Reproduce_RuleGNN/ResultsSOTA/" # Results will be saved in this folder