datasets:
  - {name: "PTC_MR_PTC_FM", validation_folds: 10, experiment_config_file: "Examples/Transfer/Configs/config_experiment.yml"}

paths:
  data:
    "Examples/Transfer/Data/" # Path to the folder containing the graph data
  properties:
    "Examples/Transfer/Data/Properties/" # Precomputed properties will be loaded from this folder
  labels:
    "Examples/Transfer/Data/Labels/" # Path to the folder containing the labels
  results:
    "Examples/Transfer/Results/" # Results will be saved in this folder
  splits:
    "Examples/Transfer/Data/Splits/" # Path to the folder containing the data splits

# determine how the input features should be transformed
input_features: {name: "node_labels", transformation: "normalize"} # use node labels and normalize them

num_workers: 1