paths:
  data:
    "GraphBenchmarks/Data/" # Path to the folder containing the graph data
  distances:
    "GraphData/Distances/" # Precomputed distances will be loaded from this folder
  results:
    "RESULTS/" # Results will be saved in this folder
  splits:
    "GraphData/DataSplits/" # Path to the folder containing the data splits
device:
  cpu
mode:
  debug # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.1
epochs:
  - 1000
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - MeanAbsoluteError
output_activation:
    None
activation:
    None
early_stopping:
  enabled:
    False
  patience:
    25
networks:
  # mixed models
  - - { layer_type: subgraph, id: 2, distances: [ 3 ] }
    - { layer_type: wl, wl_iterations: 0}
  - - { layer_type: subgraph, id: 0, distances: [1, 6, 13] }
    - { layer_type: subgraph, id: 0, distances: [13] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 100 }
    #- { layer_type: wl, wl_iterations: 0 }

linear_layers:
  0




use_features: # if True uses normlized node labels as input features, if False uses 1-vector as input features
  False
use_attributes: # if True uses node attributes instead of node labels
  False
random_variation: # if True adds random variation to the input features
  False
load_splits: # if True loads precomputed data splits (use False only for new datasets)
  True

# data options
balance_training:
  False

# Additional options for analysis only possible in debug mode
additional_options:
  draw: # draw the accuracy and loss during training
    True
  save_weights: # save the weights of the model
    False
  save_prediction_values:
    True
  plot_graphs: # Plot all graphs in the dataset
    False
  print_results: # Print accuracy and loss in the console
    True

prune:
  False

task:
  regression