datasets:
  - {name: "PTC_FM", validation_folds: 10, experiment_config_file: "Examples/TUExample/Configs/config_experiment.yml", type: "TUDataset"}
  - {name: "PTC_FR", validation_folds: 10, experiment_config_file: "Examples/TUExample/Configs/config_experiment.yml", type: "TUDataset"}

paths:
  data:
    "Examples/TUExample/Data/" # Path to the folder containing the graph data
  properties:
    "Examples/TUExample/Data/Properties/" # Precomputed properties will be loaded from this folder
  labels:
    "Examples/TUExample/Data/Labels/" # Path to the folder containing the labels
  results:
    "Examples/TUExample/Results/" # Results will be saved in this folder
  splits:
    "Examples/TUExample/Data/Splits/" # Path to the folder containing the data splits