paths:
  data:
    "../BenchmarkGraphs/DS_all/" # Path to the folder containing the graph data
  distances:
    "BenchmarkGraphs/Distances/" # Precomputed distances will be loaded from this folder
  results:
    "RESULTS/" # Results will be saved in this folder
  splits:
    "BenchmarkGraphs/Splits/" # Path to the folder containing the data splits
device:
  cpu
mode:
  debug # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.05
epochs:
  - 50
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    True
  patience:
    25
networks:
  # wl models
  # cycle models
  - - { layer_type: subgraph, id: 1, distances: [1, 2] }
    - { layer_type: induced_cycles, max_cycle_length: 5 }
  - - { layer_type: wl, wl_iterations: 1, max_node_labels: 500, distances: [1,2] }
    - { layer_type: wl, wl_iterations: 0, distances: [1,2] }
use_features: # if True uses normlized node labels as input features, if False uses 1-vector as input features
  False
use_attributes: # if True uses node attributes instead of node labels
  False
load_splits: # if True loads precomputed data splits (use False only for new datasets)
  True

# data options
balance_training:
  False

# Additional options for analysis only possible in debug mode
additional_options:
  draw: # draw the accuracy and loss during training
    True
  save_weights: # save the weights of the model
    False
  save_prediction_values:
    False
  plot_graphs: # Plot all graphs in the dataset
    False
  print_results: # Print accuracy and loss in the console
    True



