paths:
  data:
    "/home/mlai21/seiffart/BenchmarkGraphs/BenchmarkGraphs/DS_all/" # Path to the folder containing the graph data
  distances:
    "/home/mlai21/seiffart/BenchmarkGraphs/BenchmarkGraphs/DS_all/Distances/" # Precomputed distances will be loaded from this folder
  results:
    "/home/mlai21/seiffart/RESULTS/TEST/RuleGNN/Longrange/" # Results will be saved in this folder
  splits:
    "BenchmarkGraphs/Splits/" # Path to the folder containing the data splits
device:
  cpu
mode:
  experiments # if debug printing and plotting options are enabled, for the experiments mode should be 'experiments'
batch_size:
  - 128
learning_rate:
  - 0.05
epochs:
  - 50
scheduler:
  True
dropout:
  - 0.0
optimizer:
  - Adam
loss:
  - CrossEntropyLoss
early_stopping:
  enabled:
    True
  patience:
    25
networks:
  # wl models
  - - { layer_type: primary, distances: [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 1, 3, 6 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 1, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 1,2,3] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 10,11,12] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }
  - - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 1,2,3 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 10,11,12 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 500, distances: [ 20,21,22 ] }
    - { layer_type: wl, wl_iterations: 2, max_node_labels: 50000 }

use_features: # if True uses normlized node labels as input features, if False uses 1-vector as input features
  True
use_attributes: # if True uses node attributes instead of node labels
  False
load_splits: # if True loads precomputed data splits (use False only for new datasets)
  True

# data options
balance_training:
  False

# Additional options for analysis only possible in debug mode
additional_options:
  draw: # draw the accuracy and loss during training
    True
  save_weights: # save the weights of the model
    False
  save_prediction_values:
    True
  plot_graphs: # Plot all graphs in the dataset
    False
  print_results: # Print accuracy and loss in the console
    True



